version: "3.8"

services:

    mysql:
        image: mysql
        container_name: mysql
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        ports: 
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - TZ=America/Buenos Aires
            - MYSQL_DATABASE=e_commerce
        volumes: 
            - C:\ProgramData\MySQL\MySQL Server 8.0\Data:/var/lib/mysql
        
#revisar claseeeeee


        
        